name = "multiregion-user-routing"
type = "webpack"

account_id = "" # provide your Cloudflare account id
workers_dev = false
route = "example.com/*" # enter the domain which is operated by the gateway
zone_id = "" # provide the zonde id of your Cloudflare website
