version: '3.8'

services:

  #
  # Our customized NGINX OpenResty reverse proxy uses an external base URL of http://localhost
  #
  openresty:
    image: custom_openresty:1.19.3.1-8-bionic
    hostname: internal-nginx
    ports:
    - 80:80
    volumes:
    - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  #
  # A small NodeJS host for testing, which uses the same port as Curity in the multi zone setup
  #
  tinyapp:
    image: tinyapp:v1
    hostname: tinyapphost
    ports:
    - 8443:8443
